[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "nft"
  included_files = ["views/**", "models/**", "public/**", "node_modules/ejs/**"]

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

